project_name: cu-ddns

before:
  hooks:
    - ./scripts/completions.sh

builds:
  - dir: ddns
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/cloud-unpacked/cu-ddns/ddns/cmd.version={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}
    files:
      - LICENSE
      - README.md
      - completions/*

nfpms:
  - file_name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    vendor: "Cloud Unpacked"
    homepage: "https://www.CloudUnpacked.com"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A Dynamic DNS client for VPS cloud providers."
    license: MIT
    formats:
      - deb
    recommends:
      - systemd
      - cron
    bindir: /usr/bin
    contents:
      - src: ./completions/cu-ddns.bash
        dst: /usr/share/bash-completion/completions/cu-ddns
        file_info:
          mode: 0644
      - src: ./completions/cu-ddns.fish
        dst: /usr/share/fish/vendor_completions.d/cu-ddns.fish
        file_info:
          mode: 0644
      - src: ./completions/cu-ddns.zsh
        dst: /usr/share/zsh/vendor-completions/_cu-ddns
        file_info:
          mode: 0644

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"

announce:
  skip: "{{ gt .Patch 0 }}"
  mastodon:
    enabled: true
    server: "https://nanobyte.cafe"
