project_name: cu-ddns

builds:
  - dir: ddns
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/cloud-unpacked/cu-ddns/ddns/cmd.version={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}
    files:
      - LICENSE
      - README.md
    rlcp: true

nfpms:
  - file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    vendor: "Cloud Unpacked"
    homepage: "https://Feliciano.Tech"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A Dynamic DNS client for VPS cloud providers."
    license: MIT
    formats:
      - deb
    dependencies:
      - cron
    recommends:
      - systemd
    bindir: /usr/bin

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
