version: 2.1

orbs:
  gor: hubci/goreleaser@2.1

workflows:
  main:
    jobs:
      - test
      - build-binaries
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - build-binaries:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          publish: true

jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1
      - run:
          name: "Download Dependancies"
          command: go mod download
      - run:
          name: "Run Tests"
          command: go test ./...
      - save_cache:
          key: go-mod-v1
          paths:
            - "/go/pkg/mod"
  build-binaries:
    parameters:
      publish:
        type: boolean
        default: false
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - gor/install:
          version: "0.120.8"
      - unless:
          condition: << parameters.publish >>
          steps:
            - run:
                name: "Build Binaries with GoReleaser"
                command: cd ddns && goreleaser --snapshot --skip-publish --rm-dist
      - when:
          condition: << parameters.publish >>
          steps:
            - run:
                name: "Build Binaries & Publish with GoReleaser"
                command: cd ddns && goreleaser
      - persist_to_workspace:
          root: "ddns"
          paths:
            - "dist"
